### ISSUE TITLE
[build] error: Promise rejection: Error: ENOENT: no such file or directory, open...

### ISSUE THREAD

**Issue by rainerlopez** [monkick/audio-player#1]
Installed using `$ bower install --save monkick/audio-player` on my app directory.
> bower audio-player#*        not-cached https://github.com/monkick/audio-player.git#*
> bower audio-player#*           resolve https://github.com/monkick/audio-player.git#*
> bower audio-player#*          download https://github.com/monkick/audio-player/archive/v1.0.0.tar.gz
> bower audio-player#*           extract archive.tar.gz
> bower audio-player#*          resolved https://github.com/monkick/audio-player.git#1.0.0
> bower audio-player#^1.0.0      install audio-player#1.0.0
> 
> audio-player#1.0.0 bower_components\audio-player
> └── polymer#2.2.0

Imported it at header `<link rel="import" href="../bower_components/audio-player/audio-player.html">`
Added the audio-player custom tag in body.
All ok.

When tried to build my project got the error:
`error:   Promise rejection: Error: ENOENT: no such file or directory, open 'D:\REL\rel.thorp\bower_components\audio-player\bower_components\polymer\polymer-element.html'
error:   Error: ENOENT: no such file or directory, open 'D:\REL\rel.thorp\bower_components\audio-player\bower_components\polymer\polymer-element.html'
    at Error (native)`

Temporary fixed the path in the audio-player.html

Just saw that the file is correct here on github: https://github.com/monkick/audio-player/blob/master/audio-player.html

Cheers!
REL

**Comment by kazu80** [comment]
@rainerlopez 

Thank you for using. And I'm sorry that I had some bug.
I'm fixed it. So, please try again v1.0.5 (latest version)

**Comment by rainerlopez** [comment]
Thank you.
Do not be sorry at all !
Great job @monkick 
I'll test and keep on track, ok.

Cheers!
REL
